name: Upload tag

on:
  create:
    tags:
      - '*' 
jobs:
  uploadTag:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: xcodebuild clean test -project GGDevelopmentKit.xcodeproj -scheme GGDevelopmentKit -destination "platform=iOS Simulator,name=iPhone 12 Pro,OS=latest"
        #- name: AddRepo
        #run: pod repo add GGDevelopmentKit ssh://AnTonhoLAB@github.com/AnTonhoLAB/Podspecs.git
    - name: Upload tag
      run: pod repo push GGDevelopmentKit GGDevelopmentKit.podspec --allow-warnings
