name: Upload tag

on:
  create:
    tags:
      - '*' 
jobs:
  uploadTag:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: AnTonhoLAB/Podspecs
        token: ${{ secrets.ACCESS_TOKEN }}
    - name: Upload tag
      run: pod repo push GGDevelopmentKit GGDevelopmentKit.podspec --allow-warnings
