name: Upload tag

on:
  create:
    tags:
      - '*' 
jobs:
  uploadTag:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: pod repo pull
      run: pod repo add GGDevelopmentKit https://${{ secrets.ACCESS_TOKEN }}@github.com/AnTonhoLAB/Podspecs.git
    - name: pod repo push
      run: pod repo push GGDevelopmentKit GGDevelopmentKit.podspec --allow-warnings
