name: Upload tag

on:
  create:
    tags:
      - '*' 
jobs:
  uploadTag:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2}
    - name: pod repo push
        uses: maxep/pod-repo-push-action@0.1.2
        with:
        repo-url: https://AnTonhoLAB:${{ secrets.ACCESS_TOKEN }}@github.com/AnTonhoLAB/Podspecs.git
